In [ ]:
import numpy as np
import cv2
import glob

In [ ]:
np.set_printoptions(suppress=True)

In [ ]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
 
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((7*6,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:6].T.reshape(-1,2)
print(objp)
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

In [ ]:
imgs = glob.glob('Images/*.png')

used = []
for fname in imgs:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    ret, corners = cv2.findChessboardCorners(img, (7, 6), None)

    if ret == True:
        used.append(fname)
        objpoints.append(objp)
        corners = np.sort(corners, axis=1)
        print(corners)
        corners2 = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)
        imgpoints.append(corners2)

        cv2.drawChessboardCorners(img, (7, 6), corners2, ret)
        cv2.imshow(fname, img)
        if cv2.waitKey() == 27:
            cv2.destroyAllWindows()

In [45]:
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
fname = "Images/img10.png"
img = cv2.imread(fname)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, corners = cv2.findChessboardCorners(gray, (7, 6), None)
if ret == True:
    objpoints.append(objp)
    print(corners)
    corners = np.lexsort((corners[:, 1], corners[:, 0]))
    corners2 = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)
    imgpoints.append(corners2)
    print(corners2)
    cv2.drawChessboardCorners(img, (7, 6), corners2, ret)
    cv2.imshow(fname, img)
    if cv2.waitKey() == 27:
        cv2.destroyAllWindows()

[[[659.5 494. ]]

 [[614.5 467.5]]

 [[568.  441.5]]

 [[523.  414.5]]

 [[476.5 388.5]]

 [[431.  362. ]]

 [[385.5 335.5]]

 [[686.  448.5]]

 [[640.5 422.5]]

 [[594.5 395.5]]

 [[549.  369.5]]

 [[503.5 343. ]]

 [[457.5 316.5]]

 [[411.5 290.5]]

 [[712.5 402.5]]

 [[666.5 376. ]]

 [[621.  350. ]]

 [[575.5 323.5]]

 [[529.5 297. ]]

 [[484.5 271. ]]

 [[438.  244. ]]

 [[738.5 357. ]]

 [[693.5 331. ]]

 [[647.  304.5]]

 [[601.5 278. ]]

 [[555.5 251.5]]

 [[510.5 225.5]]

 [[464.5 199. ]]

 [[765.5 311.5]]

 [[720.  285. ]]

 [[674.  258.5]]

 [[628.  232. ]]

 [[582.5 205.5]]

 [[537.  179. ]]

 [[491.  152.5]]

 [[791.5 265.5]]

 [[746.  239.5]]

 [[700.  212.5]]

 [[654.5 186.5]]

 [[608.5 160.5]]

 [[563.  134. ]]

 [[517.  107.5]]]


IndexError: index 1 is out of bounds for axis 1 with size 1

In [ ]:
print(corners)
print(corners2)

In [ ]:
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
print(ret)
print(mtx)
print(dist)
print(rvecs)
print(tvecs)

In [ ]:
fx, fy, ox, oy = mtx[0, 0], mtx[1, 1], mtx[0, 2], mtx[1, 2]
print(fx, fy, ox, oy)

In [ ]:
x = 0
