In [1]:
import numpy as np
import cv2
import glob

In [2]:
np.set_printoptions(suppress=True)

In [3]:
def objp_for_size(x, y, reverse=False):

    if reverse:
        x_coords, y_coords = np.meshgrid(np.arange(x)[::-1], np.arange(y)[::-1])
    else:
        x_coords, y_coords = np.meshgrid(np.arange(x), np.arange(y))    
    
    object_points = np.stack((y_coords.flatten(), x_coords.flatten(), np.zeros_like(x_coords.flatten())), axis=-1)
    
    return object_points.astype(np.float32)

In [4]:
print(objp_for_size(7, 6))

[[0. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]
 [0. 3. 0.]
 [0. 4. 0.]
 [0. 5. 0.]
 [0. 6. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 2. 0.]
 [1. 3. 0.]
 [1. 4. 0.]
 [1. 5. 0.]
 [1. 6. 0.]
 [2. 0. 0.]
 [2. 1. 0.]
 [2. 2. 0.]
 [2. 3. 0.]
 [2. 4. 0.]
 [2. 5. 0.]
 [2. 6. 0.]
 [3. 0. 0.]
 [3. 1. 0.]
 [3. 2. 0.]
 [3. 3. 0.]
 [3. 4. 0.]
 [3. 5. 0.]
 [3. 6. 0.]
 [4. 0. 0.]
 [4. 1. 0.]
 [4. 2. 0.]
 [4. 3. 0.]
 [4. 4. 0.]
 [4. 5. 0.]
 [4. 6. 0.]
 [5. 0. 0.]
 [5. 1. 0.]
 [5. 2. 0.]
 [5. 3. 0.]
 [5. 4. 0.]
 [5. 5. 0.]
 [5. 6. 0.]]


In [5]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
objpoints = [] 
imgpoints = [] 

In [6]:
imgs = glob.glob('ugreen_left_calibration/*.png')

print(imgs)

used = []
for fname in imgs:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    ret, corners = cv2.findChessboardCorners(img, (10, 7), None)

    if ret == True:
        used.append(fname)
        objpoints.append(objp_for_size(10, 7, reverse=True))
        # corners = np.squeeze(corners)
        # print(corners.shape)
        # print(corners)
        
        corners2 = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)
        imgpoints.append(corners2)

        cv2.drawChessboardCorners(img, (10, 7), corners2, ret)
        cv2.imshow(fname, img)
        if cv2.waitKey() == 27:
            cv2.destroyAllWindows()

# print(objpoints)

['ugreen_left_calibration\\img_0.png', 'ugreen_left_calibration\\img_1.png', 'ugreen_left_calibration\\img_10.png', 'ugreen_left_calibration\\img_11.png', 'ugreen_left_calibration\\img_12.png', 'ugreen_left_calibration\\img_13.png', 'ugreen_left_calibration\\img_14.png', 'ugreen_left_calibration\\img_15.png', 'ugreen_left_calibration\\img_16.png', 'ugreen_left_calibration\\img_17.png', 'ugreen_left_calibration\\img_18.png', 'ugreen_left_calibration\\img_19.png', 'ugreen_left_calibration\\img_2.png', 'ugreen_left_calibration\\img_20.png', 'ugreen_left_calibration\\img_21.png', 'ugreen_left_calibration\\img_22.png', 'ugreen_left_calibration\\img_23.png', 'ugreen_left_calibration\\img_24.png', 'ugreen_left_calibration\\img_25.png', 'ugreen_left_calibration\\img_26.png', 'ugreen_left_calibration\\img_27.png', 'ugreen_left_calibration\\img_28.png', 'ugreen_left_calibration\\img_29.png', 'ugreen_left_calibration\\img_3.png', 'ugreen_left_calibration\\img_4.png', 'ugreen_left_calibration\\img

In [7]:
# img = cv2.imread("Images/img_test.png")
# gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# ret, corners = cv2.findChessboardCorners(img, (7, 7), None)

# if ret == True:
#     points = objp_for_size(7, 7)
#     corners2 = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)
#     cors = np.squeeze(corners2).astype(np.uint32)
#     cv2.drawChessboardCorners(img, (7, 7), corners2, ret)
#     for i in range(len(cors)):
#         org = tuple(cors[i])
#         text = str(points[i])
#         font = cv2.FONT_HERSHEY_SIMPLEX
#         fontScale = 0.5
#         color = (255, 0, 0)
#         thickness = 1
#         img = cv2.putText(img, text, org, font, fontScale, color, thickness, cv2.LINE_AA)
#     cv2.imshow("test", img)
#     if cv2.waitKey() == 27:
#         cv2.destroyAllWindows()

#     # print(points)
#     # print(corners2)
#     ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera([points], [corners2], gray.shape[::-1], None, None)
#     print(ret)
#     print(mtx)
#     print(dist)
#     print(rvecs)
#     print(tvecs)

In [11]:
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
print(ret)
print(mtx)
print(dist)
print(rvecs)
print(tvecs)

0.3168321344066692
[[550.74254131   0.         309.33499784]
 [  0.         551.22025841 226.39975186]
 [  0.           0.           1.        ]]
[[ 0.15262652  0.33736018  0.01009325  0.00782211 -1.21224862]]
(array([[-2.24523245],
       [-2.18607106],
       [-0.12775594]]), array([[-2.23926305],
       [-2.17020919],
       [-0.06287604]]), array([[-1.82920045],
       [-1.95013467],
       [ 0.3087921 ]]), array([[-2.20915467],
       [-2.15949583],
       [-0.30541573]]), array([[ 2.1900359 ],
       [ 2.10140634],
       [-0.18598706]]), array([[-2.20223757],
       [-2.15213551],
       [-0.10819987]]), array([[-1.98930947],
       [-1.90915418],
       [-0.50834741]]), array([[-2.17045829],
       [-2.07461863],
       [-0.18772383]]), array([[-1.82911033],
       [-1.7654392 ],
       [ 0.46145948]]), array([[2.09567182],
       [2.07834905],
       [0.52297145]]), array([[-1.85145709],
       [-2.33781378],
       [-0.91247388]]), array([[-2.08743127],
       [-1.69128374],


In [9]:
def unproject_position(intrinsic_matrix, camera_rotation, camera_translation, point_position):
    fx, fy, ox, oy = intrinsic_matrix[0][0], intrinsic_matrix[1][1], intrinsic_matrix[0][2], intrinsic_matrix[1][2]
    basis = basis_from_deg(camera_rotation)
    translation = np.array(camera_translation)
    basis_inv = np.linalg.inv(basis)
    translation_inv = -np.dot(basis_inv, translation)
    point_world_position = np.array(point_position)
    point_camera_position = np.dot(basis_inv, point_world_position) + translation_inv
    point_camera_position_homogenous = np.append(point_camera_position, 1)
    projection_matrix = np.array([[(fx/ox), 0, 0, 0],
                              [0, (fy/oy), 0, 0],
                              [0, 0, -1, -1],
                              [0, 0, 0, 0]]).T
    projected_point_homogenous = np.dot(projection_matrix, point_camera_position_homogenous)
    projected_point = projected_point_homogenous[:2] / projected_point_homogenous[3]
    image_pixel_coordinates = np.array([(projected_point[0] * 0.5 + 0.5) * 2 * ox, (-projected_point[1] * 0.5 + 0.5) * 2 * oy])
    return image_pixel_coordinates

In [10]:
fx, fy, ox, oy = mtx[0, 0], mtx[1, 1], mtx[0, 2], mtx[1, 2]
print(fx, fy, ox, oy)

550.742541314096 551.2202584096859 309.3349978427164 226.39975185622637
