In [55]:
import numpy as np
import cv2
import glob

In [56]:
np.set_printoptions(suppress=True)

In [57]:
def objp_for_size(x, y, reverse=False):

    if reverse:
        x_coords, y_coords = np.meshgrid(np.arange(x)[::-1], np.arange(y)[::-1])
    else:
        x_coords, y_coords = np.meshgrid(np.arange(x), np.arange(y))    
    
    object_points = np.stack((y_coords.flatten(), x_coords.flatten(), np.zeros_like(x_coords.flatten())), axis=-1)
    
    return object_points.astype(np.float32)

In [58]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

In [59]:
imgs = glob.glob('Images/*.png')

used = []
for fname in imgs:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    ret, corners = cv2.findChessboardCorners(img, (7, 6), None)

    if ret == True:
        used.append(fname)
        objpoints.append(objp_for_size(7, 6, reverse=True))
        # corners = np.squeeze(corners)
        # print(corners.shape)
        # print(corners)
        
        corners2 = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)
        imgpoints.append(corners2)

        cv2.drawChessboardCorners(img, (7, 6), corners2, ret)
        # cv2.imshow(fname, img)
        # if cv2.waitKey() == 27:
        #     cv2.destroyAllWindows()

print(objpoints)

[array([[5., 6., 0.],
       [5., 5., 0.],
       [5., 4., 0.],
       [5., 3., 0.],
       [5., 2., 0.],
       [5., 1., 0.],
       [5., 0., 0.],
       [4., 6., 0.],
       [4., 5., 0.],
       [4., 4., 0.],
       [4., 3., 0.],
       [4., 2., 0.],
       [4., 1., 0.],
       [4., 0., 0.],
       [3., 6., 0.],
       [3., 5., 0.],
       [3., 4., 0.],
       [3., 3., 0.],
       [3., 2., 0.],
       [3., 1., 0.],
       [3., 0., 0.],
       [2., 6., 0.],
       [2., 5., 0.],
       [2., 4., 0.],
       [2., 3., 0.],
       [2., 2., 0.],
       [2., 1., 0.],
       [2., 0., 0.],
       [1., 6., 0.],
       [1., 5., 0.],
       [1., 4., 0.],
       [1., 3., 0.],
       [1., 2., 0.],
       [1., 1., 0.],
       [1., 0., 0.],
       [0., 6., 0.],
       [0., 5., 0.],
       [0., 4., 0.],
       [0., 3., 0.],
       [0., 2., 0.],
       [0., 1., 0.],
       [0., 0., 0.]], dtype=float32), array([[5., 6., 0.],
       [5., 5., 0.],
       [5., 4., 0.],
       [5., 3., 0.],
       [5., 2., 

In [66]:
img = cv2.imread("Images/img_test.png")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

ret, corners = cv2.findChessboardCorners(img, (7, 7), None)

if ret == True:
    points = objp_for_size(7, 7)
    corners2 = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)
    cors = np.squeeze(corners2).astype(np.uint32)
    cv2.drawChessboardCorners(img, (7, 7), corners2, ret)
    for i in range(len(cors)):
        org = tuple(cors[i])
        text = str(points[i])
        font = cv2.FONT_HERSHEY_SIMPLEX
        fontScale = 0.5
        color = (255, 0, 0)
        thickness = 1
        img = cv2.putText(img, text, org, font, fontScale, color, thickness, cv2.LINE_AA)
    cv2.imshow("test", img)
    if cv2.waitKey() == 27:
        cv2.destroyAllWindows()

    # print(points)
    # print(corners2)
    ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera([points], [corners2], gray.shape[::-1], None, None)
    print(ret)
    print(mtx)
    print(dist)
    print(rvecs)
    print(tvecs)

0.24315654218046842
[[2511.1251446     0.          552.69873133]
 [   0.         2511.06512909  343.13412812]
 [   0.            0.            1.        ]]
[[  0.3187572  -31.27712435   0.00301731  -0.00317245  -1.96705484]]
(array([[ 2.22383994],
       [ 2.22384616],
       [-0.00055057]]),)
(array([[-2.57040146],
       [-3.36963256],
       [47.56976129]]),)


In [64]:
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
print(ret)
print(mtx)
print(dist)
print(rvecs)
print(tvecs)

0.39221438223409055
[[421.32885985   0.         576.23080988]
 [  0.         421.18511044 323.80923872]
 [  0.           0.           1.        ]]
[[-0.0004572   0.00066335  0.00026122 -0.00009024 -0.00146737]]
(array([[-1.57040112],
       [-2.72007635],
       [-0.00124001]]), array([[-0.81286856],
       [-3.03399303],
       [-0.00140376]]), array([[-2.12865988],
       [-2.12904701],
       [-0.18945019]]), array([[-2.12882907],
       [-2.12932091],
       [-0.18918512]]), array([[-2.1278356 ],
       [-2.12804592],
       [-0.19056095]]), array([[2.22157756],
       [2.22203731],
       [0.00135044]]), array([[ 2.45315191],
       [ 1.83036828],
       [-0.16192298]]), array([[-2.03211088],
       [-1.9523042 ],
       [ 0.61663049]]), array([[-2.13004438],
       [-2.13006707],
       [ 0.18447765]]), array([[ 2.14065804],
       [ 2.11975816],
       [-0.25970496]]), array([[-2.03025872],
       [-2.03021099],
       [ 0.35834004]]), array([[-1.92536255],
       [-1.92662866],

In [ ]:
fx, fy, ox, oy = mtx[0, 0], mtx[1, 1], mtx[0, 2], mtx[1, 2]
print(fx, fy, ox, oy)

421.3288598524098 421.1851104387658 576.2308098834302 323.8092387201817
